config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "articles#index"
  resources :articles do
    resources :comments
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_rich_text :body
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  has_rich_text :body
  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @pagy, @articles = pagy(Article.all)
    @image_src = "https://github.com/jbeachy21/rails-blog/blob/master/app/assets/images/railsblog.png"
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
    end
  
     
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end

  end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name, :site_URL, :github_URL, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          
          <div class="card-body">
            <% if user_signed_in? %>
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <% else %>
            <h5 class="card-title text-success"><%= article.title %></h5>
            <% end %>
           
            <p class="card-text"><%= article.body %></p>
            <% if current_user %>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago. <br>
            Edited <%= time_ago_in_words(article.updated_at) %> ago.</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<script src="https://cdn.tiny.cloud/1/pt7h8zzhh0doras6xjpegclthxhmru8jg0lv1h53u4vfrc40/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>
<div class="container-fluid">
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, class:"form-control"%>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br>

  <div>
  <textarea id="mytextarea">Hello, World!</textarea>
  <br>
  <br>
    
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
   <br>
  <div>
    <%=  form.submit "Submit", class:"btn btn-outline-primary" %>
  </div>
  <br>
  <br>
  <br>
<% end %>
</div>

app/views/articles/edit.html.erb
<div class="container-fluid">
<h1>Edit Article</h1>
</div>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="container-fluid text-center">
<% if user_signed_in? %>
<h3>Welcome user <%=  current_user.email.split(/@|Apt/, 2).first %></h3>
<% else %>
<h3>Welcome user</h3>
<%end%>


<%= Article.public_count %> articles and counting!
</div>

<br><br>
<%= render 'article' %>


<% if user_signed_in? %>
<div class="container text-center">
<%= link_to "New Article", new_article_path, class: "btn btn-outline-primary" %>
</div>
<%end%>
<br><br>


  <div class="apple_pagination text-justify">
    <%== pagy_nav(@pagy)  %>
  </div>

app/views/articles/new.html.erb
<div class="container-fluid">
<h1>New Article</h1>
</div>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="container-fluid">
<h1><%= @article.title %></h1>

<p class="lead"><%= @article.body %></p>

<br>
<br>



<% if user_signed_in? %>

 
<h3>Actions:</h3><br>  
<ul class="list-group list-group-horizontal">
  <li class="list-group-item border-0"><%= link_to "Edit", edit_article_path(@article), 
  class:"btn btn-outline-success"%></li>
  <li class="list-group-item border-0"><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, 
                  class:"btn btn-outline-danger" %></li>
</ul>
<%end%>

<br>
<br>

<h2>Comments</h2>
<%= render @article.comments %>



 
<br>
<br>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
</div>

app/views/comments/_comment.html.erb
 

<p>

 


<div class="card">
  <div class="card-header">
    <strong>By: <%= comment.commenter %></strong>
  </div>
  <div class="card-body">
    <p class="card-text"><%= comment.body %></p>
  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
            method: :delete,
            data: { confirm: "Are you sure?" }, class:"btn btn-outline-danger" %>
</p>
  </div>
</div>


<br>

app/views/comments/_form.html.erb
<script src="https://cdn.tiny.cloud/1/pt7h8zzhh0doras6xjpegclthxhmru8jg0lv1h53u4vfrc40/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter, class:"form-control" %>
    </p>
    <div class="">
    <textarea id="mytextarea">Hello, World!</textarea>
  </div>
    <p>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public', 
         :class => 'form-select' %>
    </p>
  
    <p>
      <%= form.submit 'Create Comment', :class => 'btn btn-outline-primary' %>
    </p>
  <% end %>
  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        
        <div class="collapse navbar-collapse">
        <ul class="text-white navbar-nav mb-lg-0 nav-fill w-100">
            <li><%= link_to "Rails Blog", articles_path, class:"navbar-brand" %></li>
            <li class="nav-item"><%= link_to "Articles", articles_path, class:"nav-link" %></li>
            <% if user_signed_in? %>
                <li class="nav-item"><%= link_to "Create Article", new_article_path, class:"nav-link"%></li>
                <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%></li>
                <li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%></li>
            <% else %>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%></li>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class:"nav-link"%></li>
            <%end%>
             
        </div>
    </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="image" property="og:image" content="https://github.com/jbeachy21/rails-blog/blob/master/app/assets/images/railsblog.png">
    <meta data-rh="true" property="og:image" content="https://github.com/jbeachy21/rails-blog/blob/master/app/assets/images/railsblog.png">
    <meta prefix="og: http://ogp.me/ns#" property="og:image" content="https://github.com/jbeachy21/rails-blog/blob/master/app/assets/images/railsblog.png" />

     
    <%= display_meta_tags %>
    

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <script type="text/javascript" src="/assets/tinymce.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="image_src" href="../../assets/images/railsblog.png">
    <link rel="stylesheet" type="text/css" href="trix.css">
    <script type="text/javascript" src="trix.js"></script>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    
  
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_name %>
    <%= form.text_field :project_name %>
  </div>

  <div class="field">
    <%= form.label :site_URL %>
    <%= form.text_field :site_URL %>
  </div>

  <div class="field">
    <%= form.label :github_URL %>
    <%= form.text_field :github_URL %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Project name</th>
      <th>Site url</th>
      <th>Github url</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.project_name %></td>
        <td><%= project.site_URL %></td>
        <td><%= project.github_URL %></td>
        <td><%= project.description %></td>
        <td><%= project.image %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @project.project_name %>
</p>

<p>
  <strong>Site url:</strong>
  <%= @project.site_URL %>
</p>

<p>
  <strong>Github url:</strong>
  <%= @project.github_URL %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @project.image %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>